apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: genesis
resources:
  - namespace.yaml
  - configmap-app.yaml
  - pvc-uploads.yaml
  - deployment-app.yaml
  - service-app.yaml
# secret-app.yaml: criar localmente a partir de secret-app.example.yaml
# ingress.example.yaml: aplicar à parte quando o controller existir
commonLabels:
  app.kubernetes.io/part-of: minestation
  app.kubernetes.io/managed-by: kustomize
