apiVersion: v1
kind: Service
metadata:
  name: genesis-app
  namespace: genesis
  labels:
    app.kubernetes.io/name: genesis-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: genesis-app
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
