apiVersion: v1
kind: ConfigMap
metadata:
  name: genesis-app-config
  namespace: genesis
data:
  KAFKA_ENABLED: '1'
  KAFKA_BROKERS: 'genesis-kafka-bootstrap.genesis.svc.cluster.local:9092'
  KAFKA_CLIENT_ID: 'genesis-app'
